name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install LocalTunnel
      run: npm install -g localtunnel
    - name: Create Tunnel
      run: lt --port 3389 --subdomain youruniquesubdomain --local-host 127.0.0.1
      env:
        TUNNEL_PASSWORD: ${{ secrets.TUNNEL_PASSWORD }}
